// tslint:disable
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CalcGasPriceRespVO
 * @export
 * @interface CalcGasPriceRespVo
 */
export interface CalcGasPriceRespVo {
    /**
     *
     * @type {string}
     * @memberof CalcGasPriceRespVo
     */
    chainAccountAddress: string;
    /**
     *
     * @type {number}
     * @memberof CalcGasPriceRespVo
     */
    gasCount: number;
    /**
     *
     * @type {number}
     * @memberof CalcGasPriceRespVo
     */
    payAmount: number;
}


